version: '2'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ${PWD}/app:/data/www:ro
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
  app:
    build: .
    ports:
      - "8000:8000"
